modLoader = "javafml"
loaderVersion = "[47,)"
#issueTrackerURL = ""
license = "Insert License Here"

[[mods]]
modId = "diversemodlib"
version = "${version}"
displayName = "DiverseModLib"
authors = "Me!"
description = '''
DiverseModLib!
'''
#logoFile = ""

[[dependencies.diversemodlib]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "SERVER"

[[dependencies.diversemodlib]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "SERVER"
